services:
  blog:
    build: ./docker/httpd
    expose:
      - 8080
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 60M
      mode: replicated
      replicas: 1

    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080

