apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: test-for-team2
  template:
    metadata:
      labels:
        app: test-for-team2 
    spec:
      containers:
        - name: test-for-team2
          image: esthercho7/blog:team2 
          ports:
          - containerPort: 8080
          command: ["java", "-jar", "/app.jar"]


---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: test-for-team2 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
