apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: esthercho7/blog:team2 
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 0.1m
              memory: 10Mi
            limits:
              cpu: 1m
              memory: 60Mi


---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
