global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8090']  # Spark Master의 JMX 포트

  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:8091']  # Spark Worker의 JMX 포트

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

