version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_LOG_LEVEL=INFO
    ports:
      - "8080:8080"   # Spark Master Web UI
      - "7077:7077"   # Spark Master port
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
      - SPARK_LOG_LEVEL=INFO
        #- SPARK_CONF_spark.executor.memory=2G
        #- SPARK_CONF_spark.driver.memory=2G
      - SPARK_CONF_spark.dynamicAllocation.enabled=true
      - SPARK_CONF_spark.dynamicAllocation.shuffleTracking.enabled=true
      - SPARK_CONF_spark.dynamicAllocation.minExecutors=1
      - SPARK_CONF_spark.dynamicAllocation.maxExecutors=5
      - SPARK_CONF_spark.dynamicAllocation.initialExecutors=1
      - SPARK_CONF_spark.shuffle.service.enabled=true
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

