version: "3.8"

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    deploy:
      mode: global
    networks:
      - spark-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - spark-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - spark-network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    command:
      - "/opt/bitnami/spark/bin/spark-class"
      - "-javaagent:/opt/bitnami/spark/jmx_prometheus_javaagent.jar=8090:/opt/bitnami/spark/config.yml"
      - "org.apache.spark.deploy.master.Master"
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master 포트
      - "8090:8090"  # JMX 포트
    volumes:
      - ./jmx_prometheus_javaagent-1.0.1.jar:/opt/bitnami/spark/jmx_prometheus_javaagent.jar
      - ./config.yml:/opt/bitnami/spark/config.yml
      - ./metrics.properties:/opt/bitnami/spark/conf/metrics.properties  # metrics.properties 파일 매핑
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command:
      - "/opt/bitnami/spark/bin/spark-class"
      - "org.apache.spark.deploy.worker.Worker"
      - "spark://spark-master:7077"
    ports:
      - "8081-8084:8081"  # Spark Worker Web UI 포트를 8081-8083으로 매핑
    networks:
      - spark-network
    deploy:
      replicas: 1  # 워커를 3개로 스케일링

volumes:
  grafana-data:

networks:
  spark-network:

